### ISSUE TITLE
Ошибка десириализации настроек

### ISSUE THREAD

**Issue by alexeydyomin** [LazarenkoA/prometheus_1C_exporter#11]
Добрый день.
Думаю что не я один такой) 
Прошу подсказать как правильно настроить ваш экспортер на windows 2012 сервере.
Что сделал:

- Установил git и go
- Скачал вашу репу
- Сделал  go build -o "1с_exporter.exe"
- После поправил файл конфига указав пути до RAC

![image](https://user-images.githubusercontent.com/83216620/128631417-4f4f34a1-61a6-4e2d-a3b5-7dfae2d38bf2.png)

- больше не правил никаких параметров (возможно нужно что-то еще)

- Пытаюсь запустить экспортера командой  1с_exporter.exe -port=9095 --settings=C:\prometheus_1c_exporter\settings.yaml
- И получаю след. ошибку

![image](https://user-images.githubusercontent.com/83216620/128631513-2ef6a7d5-ea5c-4a17-8200-11b0db0c2505.png)

**Comment by LazarenkoA** [comment]
Проверьте инвалидность yaml, возможно у вас проблема с табуляцией, проверить можно в любом онлайн валидаторе вот первый попавшийся 
https://codebeautify.org/yaml-validator

**Comment by alexeydyomin** [comment]
Ну я по сути не менял ничего, только путь. И валидность файл проходит

![image](https://user-images.githubusercontent.com/83216620/128631972-2880c5d9-19d5-4c06-895a-bf7932b5d359.png)

**Comment by alexeydyomin** [comment]
Спасибо, нашел проблему, ставил обратный слеш 

![image](https://user-images.githubusercontent.com/83216620/128632050-7c984b49-4995-4391-925f-288a8653ed73.png)
В целом запустить вроде получилось.

![image](https://user-images.githubusercontent.com/83216620/128632099-f0bfd28c-0ee6-4489-9074-b019539672fd.png)

Это нормальная отработка команды?
localhost:9095 должен быть доступен 

![image](https://user-images.githubusercontent.com/83216620/128632151-fe4ac997-d11d-4cbb-b31c-0dbe19df9aec.png)

**Comment by LazarenkoA** [comment]
Да это нормально, да должен быть доступен, в смысле на хосте порт должен быть открыт в фаерволе

**Comment by alexeydyomin** [comment]
Ну что-то у меня пока метрик нету.

![image](https://user-images.githubusercontent.com/83216620/128632571-d1aac998-d84c-47ba-914e-9eab017f003f.png)

Экспортер видимо не подцепился к 1с, ему явно надо указывать пользователя и пароль?

**Comment by LazarenkoA** [comment]
И это не тот url, прочитайте readme

**Comment by alexeydyomin** [comment]
Артем, извините, очень затупил.  Нашел все. 

![image](https://user-images.githubusercontent.com/83216620/128632768-60894dab-c001-4444-8245-dde9aa9ad4a7.png)

Огромное вам спасибо за ваши труды!

**Comment by LazarenkoA** [comment]
Пожалуйста
