### ISSUE TITLE
Ошибка установки соединения с кластером серверов

### ISSUE THREAD

**Issue by alexeydyomin** [LazarenkoA/prometheus_1C_exporter#13]
Добрый вечер. Подскажите пожалуйста, не сталкивались ли вы с такой проблемой - 

![image](https://user-images.githubusercontent.com/83216620/132233016-a87243c4-4386-4f2a-a17c-c8b42caddcf3.png)

Запускаю ./rac cluster list и получаю такое сообщение.

**Comment by LazarenkoA** [comment]
> Запускаю ./rac cluster list
это не относится к 1C_exporter, но в любом случае в сообщении написано причина ошибки
