### ISSUE TITLE
ClusterUser&ClusterPwd

### ISSUE THREAD

**Issue by karyazov** [LazarenkoA/prometheus_1C_exporter#15]
Добрый день!

Обнаружил также проблему с подключением к кластеру после запуска из релизного exe. Потом увидел сообщение о этой проблеме. Хотя обращение и закрыто, но в исходниках ошибка осталась, отсутствует блок добавления пароля и логина в строку параметров 
![image](https://user-images.githubusercontent.com/25343864/162374946-1f2b0485-e723-4ba5-8935-b0d4ca56126a.png)

Но я не опытный специалист по GIT и Go, поэтому могу ошибаться.

У себя запустил вставив недостающие блоки посмотрев изменения в одном из релизов. Все работает!

Спасибо!

**Comment by LazarenkoA** [comment]
Добрый вечер, логпас добавляется тут 
![image](https://user-images.githubusercontent.com/15386101/162492777-bc52bb2c-41d6-4829-bd77-3a8e913f30b5.png)

**Comment by LazarenkoA** [comment]
`У себя запустил вставив недостающие блоки посмотрев изменения в одном из релизов. Все работает!`
не понимаю тогда смысла этого issues

**Comment by karyazov** [comment]
Добрый день!
Получается можно закрыть, буду на стандартном варианте проверять у себя почему не взлетело пока вот этот кусок не вставил
![image](https://user-images.githubusercontent.com/25343864/162562004-261f982a-f9dc-42e9-9083-d4fa639cda57.png)

Еще раз спасибо за крутую программу!

**Comment by LazarenkoA** [comment]
по последнем скрине это старый вариант до исправления 
![image](https://user-images.githubusercontent.com/15386101/162566944-36c30ea3-59c2-487e-9319-b7d648637a80.png)
