### ISSUE TITLE
panic: label value "s\x94" is not valid UTF-8

### ISSUE THREAD

**Issue by Alexey-Poltavets** [LazarenkoA/prometheus_1C_exporter#16]
Добрый день!
Столкнулись с проблемой при запуске. Примечательно, что проблема возникла на одном сервере, когда отсутствует на другом тестовом сервере, то есть ошибка может зависеть от настройки окружения. 
Можете прокомментировать?
Спасибо!
//Алексей

1C_exporter.exe -port=9095 --settings=c:\TOOLS\Prometheus\1cExporter\settings.yaml
port : 9095
panic: label value "s\x94" is not valid UTF-8

goroutine 58 [running]:
github.com/prometheus/client_golang/prometheus.(*SummaryVec).WithLabelValues(0xc00018a190, 0xc0004faf00, 0x8, 0x8, 0xc000555f18, 0xc000384400)
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/summary.go:610 +0xe6
github.com/LazarenkoA/prometheus_1C_exporter/explorers.(*ExplorerSessionsMemory).StartExplore.func1(0xc0002362a0, 0xc000018508, 0x4)
        /home/runner/work/prometheus_1C_exporter/prometheus_1C_exporter/explorers/SessionsData.go:73 +0x2013
github.com/LazarenkoA/prometheus_1C_exporter/explorers.(*ExplorerSessionsMemory).StartExplore(0xc0002362a0)
        /home/runner/work/prometheus_1C_exporter/prometheus_1C_exporter/explorers/SessionsData.go:97 +0x4ab
github.com/LazarenkoA/prometheus_1C_exporter/explorers.(*BaseExplorer).Start(0xc0002362a0, 0x11c4380, 0xc0002362a0)
        /home/runner/work/prometheus_1C_exporter/prometheus_1C_exporter/explorers/BaseExplorer.go:178 +0x9e
created by main.main.func1
        /home/runner/work/prometheus_1C_exporter/prometheus_1C_exporter/main.go:62 +0xfa

**Comment by LazarenkoA** [comment]
Добрый день, приложите пожалуйста логи за последний час

**Comment by Alexey-Poltavets** [comment]
Артем,
Приложение падает сразу после старта, поэтому продолжительных логов нет. 
Я поставил уровень логирования 6, что получилось - в приложении
[Log_14.log](https://github.com/LazarenkoA/prometheus_1C_exporter/files/8473148/Log_14.log)

**Comment by LazarenkoA** [comment]
что-то не так в переменной `item`. Вот exe в нем я добавил логирования с уровнем Trace, запусти плиз, после падения логи сюда скинь
[prometheus_1C_exporter.zip](https://github.com/LazarenkoA/prometheus_1C_exporter/files/8475147/prometheus_1C_exporter.zip)

**Comment by Alexey-Poltavets** [comment]
Дефендер находит в архиве троян Trojan:Script/Oneeva.A!ml.

**Comment by Alexey-Poltavets** [comment]
Внутри зипа - исполняемый файл, но его размер на 30% больше того, что используется сейчас (14 Мб вместо 11 Мб). Это корректно?

**Comment by LazarenkoA** [comment]
да, корректно

**Comment by LazarenkoA** [comment]
> Дефендер находит в архиве троян Trojan:Script/Oneeva.A!ml.

можешь сам добавить сюда
https://github.com/LazarenkoA/prometheus_1C_exporter/blob/cc352f1a88a7dc649196f1567d72050817e92c71/explorers/SessionsData.go#L71
строку
`this.logger.WithField("item", item).Trace()`

**Comment by karyazov** [comment]
У меня после копиляции последнего релиза тоже исполняемый файл = 13Мб.
Скачал exe, запустилось успешно

**Comment by Alexey-Poltavets** [comment]
Взял исходники, добавил приведеное выражание строкой 71 в файл /explorers/SessionsData.go и собрал exe-шник.
Размер получился 13 Мб (не 14 как в приложенном zip'e).

Запускаю на выполнение, получаю 
c:\TOOLS\Prometheus\1cExporter\1C_exporter.exe -port=9095 --settings=c:\TOOLS\Prometheus\1cExporter\settings.yaml
port : 9095
panic: label value "s\x94" is not valid UTF-8

goroutine 57 [running]:
github.com/prometheus/client_golang/prometheus.(*SummaryVec).WithLabelValues(0x13b6e00?, {0xc00005d280?, 0x143dc29?, 0x14?})
        C:/Users/ap/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/summary.go:610 +0x85
github.com/LazarenkoA/prometheus_1C_exporter/explorers.(*ExplorerSessionsMemory).StartExplore.func1(0xc0002362a0, {0xc0001a4748, 0x4})
        C:/Users/ap/git/1C_exporter/explorers/SessionsData.go:73 +0x5e5
github.com/LazarenkoA/prometheus_1C_exporter/explorers.(*ExplorerSessionsMemory).StartExplore(0xc0002362a0)
        C:/Users/ap/git/1C_exporter/explorers/SessionsData.go:97 +0x454
github.com/LazarenkoA/prometheus_1C_exporter/explorers.(*BaseExplorer).Start(0xc0002362a0, {0x1ab419071a0, 0xc0002362a0})
        C:/Users/ap/git/1C_exporter/explorers/BaseExplorer.go:178 +0xbb
created by main.main.func1
        C:/Users/ap/git/1C_exporter/main.go:62 +0x131

Смотрю логи (уровень логирования 2 или 3), только две строки

{"Name":"disk","error":"The system cannot find the file specified.","level":"error","msg":"","time":"2022-04-13T08:25:46+02:00"}
{"Name":"ProcData","error":"ОС windows не поддерживается","level":"error","msg":"","time":"2022-04-13T08:25:46+02:00"}

О системе - Windows Server 2019 версия 1809

Ставлю уровень логирования 5, получаю логи

{"Name":"ClientLic","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"Name":"AvailablePerformance","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SheduleJob","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Session","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Connect","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SessionsData","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"Name":"ProcData","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"Name":"CPU","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"Name":"disk","level":"debug","msg":"Создание объекта","time":"2022-04-13T08:38:44+02:00"}
{"level":"info","msg":"Сбор метрик:SheduleJob,Connect,ProcData,ClientLic,AvailablePerformance,CPU,disk,Session,SessionsData","time":"2022-04-13T08:38:44+02:00"}
{"Name":"ClientLic","delay":60,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"ClientLic","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"ClientLic","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","cluster","list"]}
{"Name":"CPU","delay":10,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"ProcData","delay":10,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Session","delay":60,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"ProcData","error":"ОС windows не поддерживается","level":"error","msg":"","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Session","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"disk","delay":10,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Session","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","cluster","list"]}
{"Name":"Connect","delay":60,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"disk","error":"The system cannot find the file specified.","level":"error","msg":"","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Connect","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SessionsData","delay":10,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SessionsData","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SessionsData","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","cluster","list"]}
{"Name":"Connect","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","cluster","list"]}
{"Name":"SheduleJob","delay":10,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SheduleJob","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SheduleJob","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","cluster","list"]}
{"Name":"AvailablePerformance","delay":10,"level":"debug","msg":"Start","time":"2022-04-13T08:38:44+02:00"}
{"Name":"AvailablePerformance","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"AvailablePerformance","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","cluster","list"]}
{"Name":"Connect","level":"debug","msg":"Получен идентификатор кластера ","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Connect","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","infobase","summary","list","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"SheduleJob","level":"debug","msg":"Получен идентификатор кластера ","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SheduleJob","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","infobase","summary","list","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"Session","level":"debug","msg":"Получен идентификатор кластера ","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Session","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","infobase","summary","list","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"ClientLic","level":"debug","msg":"Получен идентификатор кластера ","time":"2022-04-13T08:38:44+02:00"}
{"Name":"ClientLic","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","session","list","--licenses","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"SessionsData","level":"debug","msg":"Получен идентификатор кластера ","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SessionsData","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","infobase","summary","list","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"AvailablePerformance","level":"debug","msg":"Получен идентификатор кластера ","time":"2022-04-13T08:38:44+02:00"}
{"Name":"AvailablePerformance","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","process","list","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"Connect","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Connect","level":"debug","msg":"Получен идентификатор кластера 09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Connect","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","connection","list","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"Session","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Session","level":"debug","msg":"Получен идентификатор кластера 09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25","time":"2022-04-13T08:38:44+02:00"}
{"Name":"Session","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","session","list","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"SessionsData","level":"debug","msg":"Получаем идентификатор кластера","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SessionsData","level":"debug","msg":"Получен идентификатор кластера 09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25","time":"2022-04-13T08:38:44+02:00"}
{"Name":"SessionsData","level":"debug","msg":"Выполнение команды","time":"2022-04-13T08:38:44+02:00","Исполняемый файл":"c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","Параметры":["c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe","core.cloudoffice.se:1545","session","list","--cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25"]}
{"Name":"AvailablePerformance","level":"debug","msg":"Количество данных: 1","time":"2022-04-13T08:38:44+02:00"}

**Comment by Alexey-Poltavets** [comment]
> Дефендер находит в архиве троян Trojan:Script/Oneeva.A!ml.

Думаю, что файл был сохранен как самораспаковывающийся архив и было ложнопозитивное срабатываение дефендера.

**Comment by LazarenkoA** [comment]
> > Дефендер находит в архиве троян Trojan:Script/Oneeva.A!ml.
> 
> Думаю, что файл был сохранен как самораспаковывающийся архив и было ложнопозитивное срабатываение дефендера.

нет, это обычный зип и exe

**Comment by LazarenkoA** [comment]
"Взял исходники, добавил приведеное выражание строкой 71 в файл /explorers/SessionsData.go и собрал exe-шник."
я не вижу в логе `item`, видимо что-то не так сделал

**Comment by LazarenkoA** [comment]
аа, понятно, ты с уровнем 5 запускал, запусти с уровнем 6

**Comment by Alexey-Poltavets** [comment]
Верно, запускал с уровнем 5.
Сделал логи с уровнем 6
[Log_09-edited_version.log](https://github.com/LazarenkoA/prometheus_1C_exporter/files/8487089/Log_09-edited_version.log)
.

**Comment by LazarenkoA** [comment]
ошибка из-за `"user-name": "s�"`, что там за логин такой странный?

**Comment by LazarenkoA** [comment]
я добавлю в этот блок кода "попытку"

**Comment by Alexey-Poltavets** [comment]
Спасибо за оперативную реакцию на проблему.
Имя пользователя - "sö". Странно, что вторая буква так странно транслировалась. UTF-8 поддерживает такие символы. Может какие-то другие зависимости дают такой эффект?

**Comment by LazarenkoA** [comment]
> Спасибо за оперативную реакцию на проблему. Имя пользователя - "sö". Странно, что вторая буква так странно транслировалась. UTF-8 поддерживает такие символы. Может какие-то другие зависимости дают такой эффект?
а как этот пользователь отображается в консоли если выполнить 
`c:\\Program Files (x86)\\1cv8\\8.3.20.1613\\bin\\rac.exe core.company.ru:1545 session list --cluster=09773f35-dc2b-4f0a-9d74-0c3ecf4c7f25`?

**Comment by LazarenkoA** [comment]
по проблеме закомител, можешь собрать попробовать, правда по таким пользователям данные в прометеус не поедут, но хотя б приложение не будет крашиться

**Comment by Alexey-Poltavets** [comment]
Все корректно отображается

session                          : 956a3064-9404-4f33-b9c7-3dd5830b13be
session-id                       : 1
infobase                         : c41aa96b-2489-4808-a590-85d8214f78b7
connection                       : 00000000-0000-0000-0000-000000000000
process                          : 00000000-0000-0000-0000-000000000000
user-name                        : sö
host                             :
app-id                           : WebClient

**Comment by Alexey-Poltavets** [comment]
Собрал исполняемый файл после комита - приложение не падает, для проблемного пользователя в логи попадает строка с ошибкой.
Спасибо!
