### ISSUE TITLE
Исходные коды мастера не соответствуют ветке последних изменений

### ISSUE THREAD

**Issue by SmirnoFFx** [LazarenkoA/prometheus_1C_exporter#17]
Смотрим исходные [коды мастера](https://github.com/LazarenkoA/prometheus_1C_exporter) и не находим изменений, связанных с "параметры rac --cluster-user и --cluster-pwd" - эти строки просто отсутствуют.
Смотрим [другую ветку](https://github.com/LazarenkoA/prometheus_1C_exporter/tree/cc6154a63254c5ae9ba2394e4d4e34d0efd5a977) и видим там все необходимые изменения.
Поэтому последний релиз (exe) не принимает параметры Login и Pass и не использует их. Авторизация администратора кластера не проходит.
Просьба поправить и пересобрать снова релиз. Спасибо, автор!

**Comment by karyazov** [comment]
Посмотри, плиз, ты про это же https://github.com/LazarenkoA/prometheus_1C_exporter/issues/15
У меня тоже сначала не получалось, но в итоге взлетело. Может не тот логопас подсовываешь?

**Comment by SmirnoFFx** [comment]
Да нет. Я просто в командной строке запускаю rac.exe и передаю --cluster-user и --cluster-pwd и все работает.
Но когда смотрю логи prometheus_1C_exporter, то там в тексте параметров нет --cluster-user и --cluster-pwd, т.е. они не передаются?

**Comment by PerlAmutor** [comment]
Был рефакторинг этого участка, он перенесен в файл BaseExplorer.go Т.ч. должно работать, если при переносе не было допущено ошибок.

![image](https://user-images.githubusercontent.com/87958986/163510962-94116fff-f7e0-4ba9-b350-f7d2eacf2614.png)

**Comment by karyazov** [comment]
> Да нет. Я просто в командной строке запускаю rac.exe и передаю --cluster-user и --cluster-pwd и все работает. Но когда смотрю логи prometheus_1C_exporter, то там в тексте параметров нет --cluster-user и --cluster-pwd, т.е. они не передаются?

Проверил по логам, логопас есть.
Попробуй пересобрать приложение

**Comment by SmirnoFFx** [comment]
Странная ситуация, конечно.
К сожалению пока возможности скомпилировать исходники у меня нет, поэтому использую готовый релиз.
Пытаюсь понять что не так? Может неверно указаны параметры в `settings.yaml`? Почему не подхватывает Логин/Пароль?

Я скачал последний релиз 1.4.11 для винды ([1c_exporter_Windows_x86_64.zip](https://github.com/LazarenkoA/prometheus_1C_exporter/releases/download/1.4.11/1c_exporter_Windows_x86_64.zip)), положил исполняемый файл в папку "D:\1c_exporter" и запускаю от имени Администратора:
`D:\1c_exporter\1c_exporter -port=9095 --settings=D:\1c_exporter\settings.yaml`.
Файл настроек такой: [settings.zip](https://github.com/LazarenkoA/prometheus_1C_exporter/files/8494189/settings.zip)
И соответственно в логах видим, что 
`{"Name":"Session","level":"debug","msg":"Выполнение команды","time":"2022-04-15T08:56:01+03:00","Исполняемый файл":"D:\\Program Files\\1cv8\\8.3.17.1851\\bin\\rac.exe","Параметры":["D:\\Program Files\\1cv8\\8.3.17.1851\\bin\\rac.exe","erp1-dmi:1545","session","list","--cluster=f4da8521-7f9f-41c1-8571-2e6246f1865a"]}`
Файл логов прикладываю: [Log_08.zip](https://github.com/LazarenkoA/prometheus_1C_exporter/files/8494194/Log_08.zip)
Забавно, но если просто в командной строке запустить
`D:\Program Files\1cv8\8.3.17.1851\bin>rac.exe erp1-dmi:1545 session list --cluster=f4da8521-7f9f-41c1-8571-2e6246f1865a --cluster-user=Admin --cluster-pwd=1234567890`, то в результате все работает и видим результат (т.е. порты доступны, все работает из командной строки):
```
session                          : 60f585fd-885a-4e8b-adc3-735fcc938090
session-id                       : 1
infobase                         : 2ab174e1-774a-4a23-8ca8-90146b1aa755
connection                       : 00000000-0000-0000-0000-000000000000
process                          : 00000000-0000-0000-0000-000000000000
user-name                        : ИвановАА
host                             : erpterm-dmi
app-id                           : 1CV8C
locale                           : ru_RU
started-at                       : 2022-04-15T08:48:35
last-active-at                   : 2022-04-15T08:53:48
hibernate                        : no
passive-session-hibernate-time   : 600
hibernate-session-terminate-time : 60
blocked-by-dbms                  : 0
blocked-by-ls                    : 0
bytes-all                        : 792517
bytes-last-5min                  : 791661
calls-all                        : 412
calls-last-5min                  : 412
dbms-bytes-all                   : 85362196
dbms-bytes-last-5min             : 72170206
db-proc-info                     :
db-proc-took                     : 0
db-proc-took-at                  :
duration-all                     : 97624
duration-all-dbms                : 14250
duration-current                 : 0
duration current-dbms            : 0
duration-last-5min               : 97624
duration-last-5min-dbms          : 12093
memory-current                   : 0
memory-last-5min                 : 3639024296
memory-total                     : 3639024296
read-current                     : 0
read-last-5min                   : 70042987
read-total                       : 70042987
write-current                    : 0
write-last-5min                  : 72575879
write-total                      : 72575879
duration-current-service         : 0
duration-last-5min-service       : 142
duration-all-service             : 172
current-service-name             :
cpu-time-current                 : 0
cpu-time-last-5min               : 83468
cpu-time-total                   : 83468
data-separation                  : ''
client-ip                        : 10.81.134.5

session                          : eda769f5-0b99-49fa-85fc-2841e2aed8a5
session-id                       : 2
infobase                         : 2ab174e1-774a-4a23-8ca8-90146b1aa755
connection                       : 48d0d255-94b0-4b79-b942-4aae6ead5ca7
process                          : 085c7524-9d05-4375-92ec-c115081e00b9
user-name                        : ИвановАА
host                             : erpterm-dmi
app-id                           : SrvrConsole
locale                           : ru_RU
started-at                       : 2022-04-15T08:48:51
last-active-at                   : 2022-04-15T08:53:43
hibernate                        : no
passive-session-hibernate-time   : 600
hibernate-session-terminate-time : 60
blocked-by-dbms                  : 0
blocked-by-ls                    : 0
bytes-all                        : 88
bytes-last-5min                  : 88
calls-all                        : 1
calls-last-5min                  : 1
dbms-bytes-all                   : 21345
dbms-bytes-last-5min             : 21345
db-proc-info                     :
db-proc-took                     : 0
db-proc-took-at                  :
duration-all                     : 16
duration-all-dbms                : 0
duration-current                 : 0
duration current-dbms            : 0
duration-last-5min               : 16
duration-last-5min-dbms          : 0
memory-current                   : 0
memory-last-5min                 : 402116
memory-total                     : 402116
read-current                     : 0
read-last-5min                   : 0
read-total                       : 0
write-current                    : 0
write-last-5min                  : 170
write-total                      : 170
duration-current-service         : 0
duration-last-5min-service       : 0
duration-all-service             : 0
current-service-name             :
cpu-time-current                 : 0
cpu-time-last-5min               : 15
cpu-time-total                   : 15
data-separation                  : ''
client-ip                        :
```

**Comment by karyazov** [comment]
Попробуй, вот этот exe https://github.com/LazarenkoA/prometheus_1C_exporter/issues/16#issuecomment-1096998041
Я его запускал, все работало.

В логах кстати также пишет как у меня в первой серии когда я запускал из релизного exe

**Comment by SmirnoFFx** [comment]
> Попробуй, вот этот exe [#16 (comment)](https://github.com/LazarenkoA/prometheus_1C_exporter/issues/16#issuecomment-1096998041) Я его запускал, все работало.
> 
> В логах кстати также пишет как у меня в первой серии когда я запускал из релизного exe

Да, этот релиз заработал. 
Резюме: просьба обновить актуальный релиз для винды, @LazarenkoA

**Comment by LazarenkoA** [comment]
хорошо, обновлю
