### ISSUE TITLE
Grafana бесконечно потребляет ОЗУ

### ISSUE THREAD

**Issue by SmirnoFFx** [LazarenkoA/prometheus_1C_exporter#18]
Начали тестировать мониторинг 1С средствами связки prometheus_1C_exporter + Prometheus + Grafana и столкнулись с бесконечным потреблением ОЗУ браузером (Chrome, Firefox) при использовании Time series графиков в Grafana по периоду "Last 6 hours" и обновлением данных раз в 30 секунд (или 5 минут).
Память растет на глазах и в скором времени браузер отваливается по ошибке "Out of Memory".
Как Вы решаете эту проблему?

З.Ы. У нас Prometheus 2.35.0-rc0.windows-amd65 + Grafana 8.4.7. Использовали как Chrome, так и Firefox.

**Comment by LazarenkoA** [comment]
да, графана в этом смысле не очень производительная. Нужно ограничить количество данных на странице, уменьшить кол-во дажбордов на странице. Дажборды в которых много метрик выводится вынести на отдельную страницу
