### ISSUE TITLE
SheduleJob - Проверка галки "блокировка регламентных заданий"

### ISSUE THREAD

**Issue by Butuff** [LazarenkoA/prometheus_1C_exporter#25]
Добрый день, удалось все запустить, но не получается параметр SheduleJob.
В настроечном файле указан какой то json который требуется для получения этого параметра, но как правильно его использовать?
 
# http сервис который возвращает массив json с кредами к БД
# нужно для метрики SheduleJob
# пример json:
#[
#  {
#    "Name": "hrmcorp-n17",
#    "UserName": "",
#    "UserPass": ""
#  }
#]

Имя базы и логин/пароль заполняю, комменты снимаю, но ругается на синтаксис. Есть пример правильного использования этого http сервиса?

**Comment by LazarenkoA** [comment]
т.к. для данной метрики нужны логин и пароль от базы, эспортер получает их их http сервиса, который разработчик поддерживающий базы 1С может реализовать на 1С. Сервис должен возвращать ответ в виде json (пример приведен). Если вам данная метрика не нужна, можете убрать ее из настройки

**Comment by Butuff** [comment]
Метрика нужна, т.е. надо сначала реализовать http сервис на стороне 1С чтобы он возвращал состояние блокировки регламентных заданий?
А какая верная конструкция будет в файле настроек чтобы обратиться к сервису? и сервис должен вернуть 1 или 0, этого достаточно?

**Comment by LazarenkoA** [comment]
сервис должен вернуть логин/пароль к базе, в примере конфига же написано 
https://github.com/LazarenkoA/prometheus_1C_exporter/blob/9f087b4478d2edaf97b8607fcc28f881a180b301/examples_settings.yaml#L47

**Comment by Butuff** [comment]
А к базе в примере экспортер обращается через 
 https://github.com/LazarenkoA/prometheus_1C_exporter/blob/9f087b4478d2edaf97b8607fcc28f881a180b301/examples_settings.yaml#LL57C1-L60C14

? 
Чтобы получить лог/пас

**Comment by LazarenkoA** [comment]
это урл сервиса который вернет жсон с логпасом, сервис может быть написан на чем угодно (в том числе и на 1С)

**Comment by Butuff** [comment]
Понял, спасибо большое! Будем пробовать 8)

**Comment by Butuff** [comment]
Что-то не получается =\ , если не трудно, то подскажите, пожалуйста, что делаю не так.
На стороне 1С создали http сервис, проверили его через фиддлер (есть авторизация), он все возвращает корректно, разместили его в одной из баз и он возвращает креды к этой базе.

Прописали сервис в настройках экспортера.
DBCredentials: # Не обязательный параметр
  URL:  https://xxxxxx/xxxxxx/hs/G_DO_Creds/1
  User: "admin"
  Password: "xxxxx"

В выдаваемых метриках не встречается вхождение "SheduleJob"

В логах с режимом Trace видно такие записи по всем базам:
{"Name":"SheduleJob","level":"trace","msg":"Запрашиваем информацию для базы test1","time":"2023-05-16T16:52:29+03:00"}
{"Name":"SheduleJob","level":"trace","msg":"Запрашиваем информацию для базы test_2","time":"2023-05-16T16:52:29+03:00"}
В том числе и для базы с размещенным http сервисом.

Но в логах почему то только одна запись с ошибкой и по базе в которой не размещен сервис....
{"Name":"SheduleJob","error":"для базы test3 не определен пользователь","level":"error","msg":"","time":"2023-05-16T16:52:34+03:00"}

Видимо не очень понимаю логики работы экспортера в этом случае. Может нужно в этом сервисе вернуть массивом имена и лог/пасс баз?

**Comment by Butuff** [comment]
Через браузер не отрабатывает, после ввода логина/пароля выдает ошибку:

![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/cbff6de8-6ab8-45bb-b998-c100ef80e669)

А фидлером все отрабатывает замечательно:

![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/5e9864dc-0b28-4ea0-9de7-0915b8c1c961)

**Comment by LazarenkoA** [comment]
ну видимо в этом причина. Вот когда браузер будет открывать, тогда пробуйте настроить экспортер

**Comment by Butuff** [comment]
Переделали сервис, в браузере виден ответ, после того как логин и пароль ввести.

![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/e362fff1-5a91-4030-8844-3d0c8fecb10f)

Но в метриках не появился SheduleJob

**Comment by LazarenkoA** [comment]
но ведь тут 
https://github.com/LazarenkoA/prometheus_1C_exporter/blob/9f087b4478d2edaf97b8607fcc28f881a180b301/examples_settings.yaml#L47-L56C1

не такой json, там массив объектов

**Comment by Butuff** [comment]
Ок, а имя массива не важно?

**Comment by Butuff** [comment]
В таком формате?

![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/fe52ebda-8549-4b2f-948c-c0d27b95f046)

**Comment by Butuff** [comment]
Так массив формируется в 1С через ЗаписьJSON.
Переделал на строку просто, вот так возвращает - 
![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/ae9b1bd9-0a67-4dcd-a7af-82664166f45b)

без изменений, коннекта по http соединению в базе не вижу, метрика тоже не появилась.
В логах есть ошибка что не определен пользователь, но я для этой базы и не прописывал креды в сервисе, не может из-за этого не работать?

**Comment by Butuff** [comment]
> Так массив формируется в 1С через ЗаписьJSON. Переделал на строку просто, вот так возвращает - ![image](https://user-images.githubusercontent.com/133659023/239548372-ae9b1bd9-0a67-4dcd-a7af-82664166f45b.png)
> 
> без изменений, коннекта по http соединению в базе не вижу, метрика тоже не появилась. В логах есть ошибка что не определен пользователь, но я для этой базы и не прописывал креды в сервисе, не может из-за этого не работать?

Поправил разделение элементов массива на запятую.

**Comment by LazarenkoA** [comment]
А почему у вас разделение элементов массива через ; ?
Приложите сюда этот жсон, есть сомнение что он вообще валидный

**Comment by LazarenkoA** [comment]
еще нужен конфиг

**Comment by LazarenkoA** [comment]
а какую версию экспортера вы используете? Я эти правки вносил Oct 12, 2022

**Comment by Butuff** [comment]
Вроде актуальную скачивал отсюда:
https://github.com/LazarenkoA/prometheus_1C_exporter/releases/download/1.4.18/1c_exporter_Windows_x86_64.zip

![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/7a98e354-c0e7-4d9a-a63a-98e4a75252ee)

![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/9e294930-1ec7-4a98-8abf-55731188947b)

октябрьских релизов не вижу.

**Comment by LazarenkoA** [comment]
пересобери актуальный, релизы я давненько не обновлял

**Comment by LazarenkoA** [comment]
можно, вечером постараюсь вынести настройку скипать проверку или нет в конфиг

**Comment by Butuff** [comment]
Отлично, спасибо большое!

**Comment by LazarenkoA** [comment]
добавил https://github.com/LazarenkoA/prometheus_1C_exporter/blob/master/examples_settings.yaml#L61

**Comment by Butuff** [comment]
Спасибо, достаточно конфиг изменить и перезапустить службу?

**Comment by LazarenkoA** [comment]
пересобрать бинарь и добавить флаг в конфиг

**Comment by Butuff** [comment]
Пересобрал, ошибка ушла, теперь другие ошибки в логе:
{"error":"REST вернул код возврата 403","level":"error","msg":"ошибка получения данных по БД","time":"2023-05-26T11:43:49+03:00"}
{"error":"unexpected end of JSON input","level":"error","msg":"не удалось десериализовать данные от REST","time":"2023-05-26T11:43:49+03:00"}

Лог - https://cloud.mail.ru/public/7V2p/SA3aUwddh

**Comment by LazarenkoA** [comment]
попробовал твой жсон вставить в тест, тест проходит, значит проблема не в жсоне
```json
[{"Name": "sat_doc","UserName": "Admin","UserPass": ""},{"Name": "sat_buh","UserName": "Администратор","UserPass": ""},{"Name": "sat_zup_30","UserName": "Администратор","UserPass": ""},{"Name": "sat_uat","UserName": "Администратор","UserPass": ""}]
```

возможно в body добавляется что-то лишнее. Попробуй выполнить `curl url сервиса > out.txt` и приложить сюда out.txt (можно прям сюда, не обязательно выкладывать в mail cloud)

вот так:
[Log_11.log](https://github.com/LazarenkoA/prometheus_1C_exporter/files/11573573/Log_11.log)

**Comment by Butuff** [comment]
Готово 
[out.txt](https://github.com/LazarenkoA/prometheus_1C_exporter/files/11573706/out.txt)

**Comment by LazarenkoA** [comment]
открой этот файл и посмотри что в нем

**Comment by Butuff** [comment]
В общем еще разбираюсь с ошибкой... видимо что-то с настройками IIS или публикации базы и сервиса в ней.
Странно что и фиддлер и просто через браузер аутентификация отрабатывает и результат выдает.

**Comment by LazarenkoA** [comment]
может есть 301 редирект?

**Comment by Butuff** [comment]
Я, честно не силен в администрировании IIS но чтобы заработал мониторинг графаны из вне по ссылке мы ставили на IIS доп. модули по этой инструкции - https://grafana.com/tutorials/iis/
Там перезапись адреса и обратный прокси.
Мониторинг на таком адресе - https://1c_xxxxxxx_.ru/monitoring/grafana/d/cf2c28b7-1b8c-419e-88fc-b79cc84cc348/1c-metrics?orgId=1
А сервис на https://1c_xxxxxxxx_.ru/1c_base/hs/GEH_DO_Creds/1

В IIS везде разрешена анонимная проверка подлинности. Остальная проверка отключена.

Переопределение такое:
![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/5dbe2adb-0275-4c2e-b418-4065e9eaae46)

Сопоставление обработчиков одинаковое как у публикуемой базы так и у страницы с мониторингом.
![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/8926e5bb-da51-4c50-b61c-aeef16d45136)
C:\Program Files (x86)\1cv8\8.3.22.1750\bin\wsisapi.dll

**Comment by Butuff** [comment]
Кстати в журнале базы где сервис размещен вижу запросы к сервису и ошибок вроде нет

![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/133659023/9363c736-4035-40a2-8643-c853b836714d)
