### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by komil4** [LazarenkoA/prometheus_1C_exporter#29]
Запустил экспортер, метрики собирались, но в какой то момент перестали, пытался перезапустить, работает некоторое время, потом вылетает с ошибкой.

<img width="987" alt="Снимок экрана 2023-06-14 в 09 22 54" src="https://github.com/LazarenkoA/prometheus_1C_exporter/assets/56590070/e68113e2-eccf-417b-a624-90b44c91f799">

**Comment by zakisss** [comment]
Аналогично:

1C_exporter.exe -port=9093 --settings=Intalev.yaml
port : 9093
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x154c179]

goroutine 8 [running]:
github.com/LazarenkoA/LogrusRotate.(*watcher).Cancel(0x0)
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:99 +0x19
github.com/LazarenkoA/LogrusRotate.(*Rotate).DeleteEmptyFile(0xc0001763f0, 0xc0001920a0)
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:287 +0x485
github.com/LazarenkoA/LogrusRotate.(*Rotate).Start.func2.1({0xc000022bc0, 0x39}, {0x18514a0, 0xc0000cd260}, {0xc0001dfe10?, 0x144667a?})
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:219 +0xa5
path/filepath.walk({0xc000022bc0, 0x39}, {0x18514a0, 0xc0000cd260}, 0xc0001dffb0)
        /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:438 +0xba
path/filepath.walk({0xc0000228c0, 0x31}, {0x18514a0, 0xc0000cce70}, 0xc0001dffb0)
        /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:458 +0x285
path/filepath.Walk({0xc0000228c0, 0x31}, 0xc000061fb0)
        /opt/hostedtoolcache/go/1.19.9/x64/src/path/filepath/path.go:521 +0x6c
github.com/LazarenkoA/LogrusRotate.(*Rotate).Start.func2()
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:208 +0xba
created by github.com/LazarenkoA/LogrusRotate.(*Rotate).Start
        /home/runner/go/pkg/mod/github.com/!lazarenko!a/!logrus!rotate@v1.0.2/rotate.go:206 +0x445

**Comment by LazarenkoA** [comment]
ошибку исправил, соберите последнюю версию вручную
