### ISSUE TITLE
Прошу дать рабочий пример настройки Grafana

### ISSUE THREAD

**Issue by khorevaa** [LazarenkoA/prometheus_1C_exporter#3]
Доброго времени.
Предлагаю в репо добавить рабочий конфиг Grafana для более правильного старта проекта

**Comment by LazarenkoA** [comment]
дополнил README

**Comment by justficks** [comment]
Скорее всего, @khorevaa просила добавить json дашборда.

Настройки дашборда > JSON Model

**Comment by LazarenkoA** [comment]
> Скорее всего @khorevaa просила добавить json дашборда.
> 
> Настройки дашборда > JSON Model
> 
> Я бы тоже был очень признателен, чтобы у меня сразу развернулась доска как у вас на примере)) Либо я слепой и не вижу этого в репозитория

ну вообще данный проект для прометея а не графаны, дажборды необязательно нужно визуализировать в графане. К тому же без объявленных переменных все равно работать не будет
![image](https://user-images.githubusercontent.com/15386101/218752655-7e73e698-4b76-4bad-8da9-4b3ba8d12590.png)
а переменные в жсон с дажбордами не выгружаются
