### ISSUE TITLE
Экспортёр не запускается в виде службы.

### ISSUE THREAD

**Issue by Simoffsky** [LazarenkoA/prometheus_1C_exporter#34]
sc create "1c_exporter" "\"C:\1c_exporter\prometheus_1C_exporter.exe\" --settings=settings.yaml"
(гитхаб съел экранированные при помощи слэша кавычки)

При запуске службы пишет:
"Ошибка 1053: Сервис не ответил на запрос своевременно"

При этом если запускать просто из под консоли, не в виде службы, то работает нормально.

**Comment by LazarenkoA** [comment]
из readme 
"можно воспользоваться приложением [nssm](https://www.nssm.cc/download) для запуска экспортера в виде службы."
т.е. для работы экспортера как служба нужно использовать приложение nssm.

**Comment by LazarenkoA** [comment]
Добавил возможность запуска без nssm
