### ISSUE TITLE
Динамическое получение пути к rac.exe

### ISSUE THREAD

**Issue by rerime** [LazarenkoA/prometheus_1C_exporter#35]
Возможно ли это? Чтобы каждый раз не перезапускать экспортер и не менять конфиг.

**Comment by LazarenkoA** [comment]
а что значит "каждый раз менять конфиг"? Зачем его менять, опишите подробнее вашу ситуацию, мне никогда такого не приходилось делать, раз настроил и работает, разве что после обновление платформы. Но ведь когда вы обновляете платформу в реестре вы так же путь к ragent меняете руками.
