### ISSUE TITLE
Получение метрик по всем кластерам одного сервера приложений 

### ISSUE THREAD

**Issue by PonamarevMV** [LazarenkoA/prometheus_1C_exporter#38]
Добрый день! 

Подскажите, есть ли возможность указания в конфигурационном файле, что необходимо собирать метрики со всех кластеров на одном сервере.
На текущий момент, на сколько я смог разобраться, метрики собираются только с одного кластера, даже при наличии нескольких.

Спасибо!

**Comment by LazarenkoA** [comment]
нет, такой возможности нет. Можно запустить два экземпляра экспортера с разными настройками RAC

**Comment by PonamarevMV** [comment]
Большое спасибо за ответ, будем пробовать!

**Comment by PonamarevMV** [comment]
Не получилось разобраться, можете подсказать, где указать ID кластера 1С, что бы запустить сбор метрик двумя экспортёрами разных кластеров 1С ?

**Comment by LazarenkoA** [comment]
ID кластера указывать не нужно, нужно указать разные настройки подключения к кластеру https://github.com/LazarenkoA/prometheus_1C_exporter/blob/96499e94804b5f03a120d5fb58fcdd5b46ba1226/examples_settings.yaml#L63
