### ISSUE TITLE
При запуске на windows 

### ISSUE THREAD

**Issue by Auzborn123** [LazarenkoA/prometheus_1C_exporter#39]
{"L":"ERROR","T":"2024-02-13T11:56:46.044+0300","N":"base","M":"ОС windows не поддерживается"}
{"L":"ERROR","T":"2024-02-13T11:56:56.046+0300","N":"base","M":"ОС windows не поддерживается"}
{"L":"ERROR","T":"2024-02-13T11:56:56.811+0300","M":"Произошла ошибка:\n\t Произошла ошибка выполнения при попытки получить идентификатор кластера: \n\tВыполнение команды прервано по таймауту\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 cluster list]\n\t\n"}
{"L":"ERROR","T":"2024-02-13T11:56:56.811+0300","M":"Произошла ошибка:\n\t Не удалось получить идентификатор кластера\n"}
{"L":"ERROR","T":"2024-02-13T11:56:57.533+0300","N":"SessionsData","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 session list --cluster=]\n\tStdErr:\ufffd訡\ufffd\ufffd ࠧ\ufffd\ufffd\ufffd\ufffd \ufffd\ufffdࠬ\ufffd\ufffd\ufffd\ufffd: cluster\r\n\n"}
{"L":"ERROR","T":"2024-02-13T11:56:58.938+0300","M":"Произошла ошибка:\n\t Произошла ошибка выполнения при попытки получить идентификатор кластера: \n\tВыполнение команды прервано по таймауту\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 cluster list]\n\t\n"}
{"L":"ERROR","T":"2024-02-13T11:56:58.938+0300","M":"Произошла ошибка:\n\t Не удалось получить идентификатор кластера\n"}
{"L":"ERROR","T":"2024-02-13T11:56:59.751+0300","N":"AvailablePerformance","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 process list --cluster=]\n\tStdErr:\ufffd訡\ufffd\ufffd ࠧ\ufffd\ufffd\ufffd\ufffd \ufffd\ufffdࠬ\ufffd\ufffd\ufffd\ufffd: cluster\r\n\n"}
{"L":"ERROR","T":"2024-02-13T11:56:59.751+0300","N":"AvailablePerformance","M":"Произошла ошибка: Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 process list --cluster=]\n\tStdErr:\ufffd訡\ufffd\ufffd ࠧ\ufffd\ufffd\ufffd\ufffd \ufffd\ufffdࠬ\ufffd\ufffd\ufffd\ufffd: cluster\r\n\n"}
{"L":"ERROR","T":"2024-02-13T11:57:06.045+0300","N":"base","M":"ОС windows не поддерживается"}
{"L":"ERROR","T":"2024-02-13T11:57:11.062+0300","M":"Произошла ошибка:\n\t Произошла ошибка выполнения при попытки получить идентификатор кластера: \n\tВыполнение команды прервано по таймауту\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 cluster list]\n\t\n"}
{"L":"ERROR","T":"2024-02-13T11:57:11.062+0300","M":"Произошла ошибка:\n\t Не удалось получить идентификатор кластера\n"}
{"L":"ERROR","T":"2024-02-13T11:57:11.062+0300","M":"Произошла ошибка:\n\t Произошла ошибка выполнения при попытки получить идентификатор кластера: \n\tВыполнение команды прервано по таймауту\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 cluster list]\n\t\n"}
{"L":"ERROR","T":"2024-02-13T11:57:11.062+0300","M":"Произошла ошибка:\n\t Произошла ошибка выполнения при попытки получить идентификатор кластера: \n\tВыполнение команды прервано по таймауту\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 cluster list]\n\t\n"}
{"L":"ERROR","T":"2024-02-13T11:57:11.062+0300","M":"Произошла ошибка:\n\t Не удалось получить идентификатор кластера\n"}
{"L":"ERROR","T":"2024-02-13T11:57:11.062+0300","M":"Произошла ошибка:\n\t Не удалось получить идентификатор кластера\n"}
{"L":"ERROR","T":"2024-02-13T11:57:11.791+0300","N":"Session","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 session list --cluster=]\n\tStdErr:\ufffd訡\ufffd\ufffd ࠧ\ufffd\ufffd\ufffd\ufffd \ufffd\ufffdࠬ\ufffd\ufffd\ufffd\ufffd: cluster\r\n\n"}
{"L":"ERROR","T":"2024-02-13T11:57:11.797+0300","N":"ClientLic","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 session list --licenses --cluster=]\n\tStdErr:\ufffd訡\ufffd\ufffd ࠧ\ufffd\ufffd\ufffd\ufffd \ufffd\ufffdࠬ\ufffd\ufffd\ufffd\ufffd: cluster\r\n\n"}
{"L":"ERROR","T":"2024-02-13T11:57:11.799+0300","N":"Connect","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 connection list --cluster=]\n\tStdErr:\ufffd訡\ufffd\ufffd ࠧ\ufffd\ufffd\ufffd\ufffd \ufffd\ufffdࠬ\ufffd\ufffd\ufffd\ufffd: cluster\r\n\n"}
{"L":"ERROR","T":"2024-02-13T11:57:12.546+0300","M":"Произошла ошибка:\n\t Произошла ошибка выполнения при попытки получить идентификатор кластера: \n\tВыполнение команды прервано по таймауту\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 cluster list]\n\t\n"}
{"L":"ERROR","T":"2024-02-13T11:57:12.546+0300","M":"Произошла ошибка:\n\t Не удалось получить идентификатор кластера\n"}
{"L":"ERROR","T":"2024-02-13T11:57:13.426+0300","N":"SessionsData","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe localhost:1540 session list --cluster=]\n\tStdErr:\ufffd訡\ufffd\ufffd ࠧ\ufffd\ufffd\ufffd\ufffd \ufffd\ufffdࠬ\ufffd\ufffd\ufffd\ufffd: cluster\r\n\n"}

**Comment by LazarenkoA** [comment]
по какой-то причине у вас команда 

C:\Program Files\1cv8\8.3.18.1698\bin\rac.exe localhost:1540 cluster list

прерывается по таймауту, если ее выполнить в консоли, она нормально выполняется, или с ощутимой задержкой?

**Comment by slothfk** [comment]
> C:\Program Files\1cv8\8.3.18.1698\bin\rac.exe localhost:1540 cluster list

а вообще нормально что там `localhost:1540`? Вроде `localhost:1545` по-умолчанию, не?

**Comment by Auzborn123** [comment]
> по какой-то причине у вас команда
> 
> C:\Program Files\1cv8\8.3.18.1698\bin\rac.exe localhost:1540 cluster list
> 
> прерывается по таймауту, если ее выполнить в консоли, она нормально выполняется, или с ощутимой задержкой?

log зацикливается, запускаю как раз таки через cmd, а выполняется достаточно быстро

{"L":"ERROR","T":"2024-02-14T12:09:27.393+0300","N":"base","M":"ОС windows не поддерживается"}
{"L":"ERROR","T":"2024-02-14T12:09:37.406+0300","N":"base","M":"ОС windows не поддерживается"}
{"L":"ERROR","T":"2024-02-14T12:09:42.407+0300","M":"Произошла ошибка:\n\t Произошла ошибка выполнения

**Comment by LazarenkoA** [comment]
нужно указывать порт ras

**Comment by Auzborn123** [comment]
Извиняюсь, поменял порт на 1545. Теперь в log попадает id кластера, но дальше тоже ошибка 

{"L":"ERROR","T":"2024-02-14T13:40:37.751+0300","N":"base","M":"ОС windows не поддерживается"}
{"L":"ERROR","T":"2024-02-14T13:40:39.354+0300","N":"AvailablePerformance","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 process list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:39.354+0300","N":"AvailablePerformance","M":"Произошла ошибка: Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 process list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:39.383+0300","N":"Connect","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 connection list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:39.420+0300","N":"SheduleJob","M":"ошибка получения списка баз: Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 infobase summary list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:39.544+0300","N":"ClientLic","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 session list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --licenses --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:39.545+0300","N":"SessionsData","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 session list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:39.766+0300","N":"Session","M":"Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 session list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:40.105+0300","N":"SessionsData","M":"ошибка получения списка баз: Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 infobase summary list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:40.121+0300","N":"Connect","M":"ошибка получения списка баз: Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 infobase summary list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}
{"L":"ERROR","T":"2024-02-14T13:40:40.552+0300","N":"Session","M":"ошибка получения списка баз: Произошла ошибка запуска:\n\terr:exit status 0xffffffff\n\tПараметры: [C:\\Program Files\\1cv8\\8.3.18.1698\\bin\\rac.exe 1csrv:1545 infobase summary list --cluster-user=.\user1cv83_RAS --cluster-pwd=password --cluster=2352d138-3261-4081-8f2b-cafbcfefe963]\n\tStdErr:\ufffd訡\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd樨 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\ufffd\ufffd\r\n\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd \ufffd\ufffd⥭\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd஢\ufffd\ufffd\r\n\n"}



При этом если делать через утилиту rac, то данные выводятся
![image](https://github.com/LazarenkoA/prometheus_1C_exporter/assets/42992103/739a5893-5037-4d21-8e11-88492b2bc8fb)

**Comment by Auzborn123** [comment]
Спасибо за помощь, разобрался)
