### ISSUE TITLE
Экспортер странно работает с версией 1С 8.3.18.1208

### ISSUE THREAD

**Issue by demokom-gmail-com** [LazarenkoA/prometheus_1C_exporter#4]
После запуска экспортера в качестве службы на Linux-сервере, он постоянно загружает 1 ядро процессора на 100%
32356 usr1cv8   20   0  715168  19156   8776 S 100,0  0,1   1:55.78 1c_exporter
Вроде бы такого быть не должно.

**Comment by LazarenkoA** [comment]
какую версию использовали, или собрали из мастера? Что в логи он пишет?

**Comment by demokom-gmail-com** [comment]
Версия последняя, брал у вас уже готовый.
В логе ничего необычного:

{"Name":"ClientLic","level":"trace","msg":"Lock","time":"2021-01-04T17:00:39+03:00"}
{"Name":"ClientLic","level":"trace","msg":"Старт итерации таймера","time":"2021-01-04T17:00:39+03:00"}
{"Name":"ClientLic","level":"trace","msg":"getLic start","time":"2021-01-04T17:00:39+03:00"}
{"level":"debug","msg":"Получаем идентификатор кластера","time":"2021-01-04T17:00:39+03:00"}
{"level":"debug","msg":"Получен идентификатор кластера 9aed9664-bbed-4ff6-acca-f822e7953f0f","time":"2021-01-04T17:00:39+03:00"}
{"Command":["/opt/1cv8/x86_64/8.3.18.1208/rac","session","list","--licenses","--cluster=9aed9664-bbed-4ff6-acca-f822e7953f0f"],"Name":"ClientLic","level":"trace","msg":"Выполняем команду","time":"2021-01-04T17:00:39+03:00"}
{"level":"debug","msg":"Выполнение команды","time":"2021-01-04T17:00:39+03:00","Исполняемый файл":"/opt/1cv8/x86_64/8.3.18.1208/rac","Параметры":["/opt/1cv8/x86_64/8.3.18.1208/rac","session","list","--licenses","--cluster=9aed9664-bbed-4ff6-acca-f822e7953f0f"]}
{"level":"trace","msg":"Парс многострочного результата","time":"2021-01-04T17:00:39+03:00"}
{"level":"trace","msg":"Парс результата","time":"2021-01-04T17:00:39+03:00"}
{"level":"trace","msg":"Парс результата","time":"2021-01-04T17:00:39+03:00"}
{"level":"trace","msg":"Парс результата","time":"2021-01-04T17:00:39+03:00"}
{"level":"trace","msg":"Парс результата","time":"2021-01-04T17:00:39+03:00"}
{"Name":"ClientLic","level":"trace","msg":"getLic return","time":"2021-01-04T17:00:39+03:00"}
{"Name":"ClientLic","level":"trace","msg":"Количество лиц. 3","time":"2021-01-04T17:00:39+03:00"}
{"Name":"ClientLic","level":"trace","msg":"return","time":"2021-01-04T17:00:39+03:00"}
{"Name":"ClientLic","level":"trace","msg":"Unlock","time":"2021-01-04T17:00:39+03:00"}

**Comment by LazarenkoA** [comment]
на других платформах не было проблем или не пробовали?

**Comment by demokom-gmail-com** [comment]
По правде говоря на предыдущей платформе было тоже самое, но я подумал, что обновление поможет, потому что на ней были еще и какие-то глюки с RAS.
Может есть смысл собрать из исходников?
У меня сейчас Ubuntu 18, postrgesql, сервер 1С, apache для web клиентов, RAS запущен в режиме демона.

**Comment by demokom-gmail-com** [comment]
Собрал из исходников, все ок, спасибо за вашу работу.

**Comment by LazarenkoA** [comment]
обновлю релиз
