### ISSUE TITLE
host в метрике

### ISSUE THREAD

**Issue by Auzborn123** [LazarenkoA/prometheus_1C_exporter#40]
Добрый день, в метрике host подставляется значение "имя сервера", а не хоста на котором запущенна сессия.
Подскажите так и задумано?
SessionsData{appid="1CV8C",base="base",datatype="memorytotal",host="1csrv",id="46",servicename="",startedat="2024-02-08 13:29:00",user="user",quantile="0.5"} 5.255222024e+09

При этом в логе host указывается верно
{"L":"DEBUG","T":"2024-02-15T09:20:57.636+0300","N":"Session","M":"Парс результата","strIn":"\nsession                          : a63cd205-4afd-44ef-be34-aa1a902fc245\nsession-id 132270\ncnuser-name: user\nhost: srv-terminal\napp-id: 1CV8C

**Comment by LazarenkoA** [comment]
черт его знает, я уже и не помню ))
Поменять то нет проблем, но боюсь это может что-т отломать у тех кто завязался на это значение сейчас

**Comment by Auzborn123** [comment]
Может можно вывести отдельной переменной?
