### ISSUE TITLE
Запуск в качестве службы Windows

### ISSUE THREAD

**Issue by gygabites** [LazarenkoA/prometheus_1C_exporter#41]
Установил службу Windows через install.bat, но при попытке запуска сразу завершается.
Логи даже не успевают записаться.
Из журнала Windows:
- "Превышение времени ожидания (30000 мс) при ожидании подключения службы "1C Prometheus exporter".";
- "Сбой при запуске службы "1C Prometheus exporter" из-за ошибки 
Служба не ответила на запрос своевременно.".

**Comment by LazarenkoA** [comment]
какую версию экспортера используете?

**Comment by LazarenkoA** [comment]
хорошо. Батник все же был добавлен как ознакомительный пример. Закрываю
