### ISSUE TITLE
Какая система оповещений используется?

### ISSUE THREAD

**Issue by metal-doctor** [LazarenkoA/prometheus_1C_exporter#5]
Мониторинг это очень хорошо, но так же необходима система оповещений.
У prometheus есть система оповещений: alertmanager. 
Именно она используется или что-то другое?

**Comment by LazarenkoA** [comment]
данный вопрос не относится непосредственно к экспортеру, он больше к прометеусу имеет отношение. У нас да, alertmanager

**Comment by metal-doctor** [comment]
Спасибо за ответ.
