### ISSUE TITLE
Почему для сбора данных ОС не используются готовые экспортеры?

### ISSUE THREAD

**Issue by metal-doctor** [LazarenkoA/prometheus_1C_exporter#6]
Есть готовые экспортеры для [unix](https://github.com/prometheus/node_exporter) и windows систем.
Можно было бы подготовить настройки и использовать готовый функционал, а разработку сосредоточить только на данных сервера 1С?

**Comment by LazarenkoA** [comment]
"Можно было бы подготовить настройки и использовать готовый функционал, а разработку сосредоточить только на данных сервера 1С?"
да, можно. Если у вас например используется другой экспортер для сбора метрик по памяти, по диску, в данном экспортере можно просто отключить сбор этих показателей (в конфиге). Если интересно почему я добавил эти метрики в свой экспортер, это было эволюционно, т.к. железо на нашем проекте мониторится заббиксом, а там тех метрик что я добавил в экспортер нет.

**Comment by metal-doctor** [comment]
Да, было интересно почему.
Спасибо за ответ.
