### ISSUE TITLE
Есть функционал отправки метрик как push сообщений?

### ISSUE THREAD

**Issue by metal-doctor** [LazarenkoA/prometheus_1C_exporter#7]
Prometheus использует модель pull запросов для получения показателей. Такой подход удобен, если prometheus и наблюдаемый сервер находятся "рядом", но при необходимости сбора показателей на "удаленных" серверах гораздо удобнее и безопаснее использовать модель push запросов.

Планируется или может быть есть уже такой функционал?

Для подобных push сообщений для мониторинга ОС использую приложение telegraf и экспортирование в формате graphite, а на стороне prometheus - graphite-exporter.

**Comment by LazarenkoA** [comment]
этот вопрос стоит задать тут https://github.com/prometheus/prometheus

**Comment by metal-doctor** [comment]
Prometheus использует модель pull запросов для получения показателей и вряд ли это будет меняться. Кому нужна модель push сообщений при работе с Prometheus должен думать об этом и реализовывать сам.
Я понял, что в данном решении нет такого функционала. Спасибо за ответ.
